---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: Retrieves all categories
      tags:
      - categories
      responses:
        '200':
          description: categories found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
    post:
      summary: Create new category
      tags:
      - categories
      parameters: []
      responses:
        '200':
          description: Sucessfully added data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                required:
                - name
        '404':
          description: Failed to add data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/categories/{id}":
    get:
      summary: Find category by id
      tags:
      - categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully find data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '404':
          description: Failed to find data
    put:
      summary: Update category by id
      tags:
      - categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully updated data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '404':
          description: Failed to update data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Delete category by id
      tags:
      - categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully deleted data
        '404':
          description: Failed to delete data
  "/depots":
    get:
      summary: Retrieves all depots
      tags:
      - depots
      responses:
        '200':
          description: depots found
          content:
            application/json:
              schema:
                type: object
                properties:
                  depots:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        address:
                          type: string
    post:
      summary: Create new depot
      tags:
      - depots
      parameters: []
      responses:
        '200':
          description: Sucessfully added data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      address:
                        type: string
                required:
                - name
                - address
        '404':
          description: Failed to add data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
              required:
              - name
              - address
  "/depots/{id}":
    get:
      summary: Find depot by id
      tags:
      - depots
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully find data
          content:
            application/json:
              schema:
                type: object
                properties:
                  depots:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      address:
                        type: string
        '404':
          description: Failed to find data
    put:
      summary: Update depot by id
      tags:
      - depots
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully updated data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      address:
                        type: string
        '404':
          description: Failed to update data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
              required:
              - name
              - address
    delete:
      summary: Delete depot by id
      tags:
      - depots
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully deleted data
        '404':
          description: Failed to delete data
  "/profile":
    get:
      summary: Retrieves a profile
      tags:
      - profile
      parameters: []
      responses:
        '200':
          description: Profile found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      name:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      address:
                        type: string
                      balance:
                        type: float
                      role:
                        type: string
                required:
                - name
                - username
                - email
                - address
                - balance
                - role
        '404':
          description: Profile not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/users/sign_up":
    post:
      summary: Create new user
      tags:
      - users
      parameters: []
      responses:
        '200':
          description: Sucessfully Create User
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                  token:
                    type: string
                  refresh_token:
                    type: string
        '422':
          description: Failed to Create User!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    email:
                      type: string
                    name:
                      type: string
                    address:
                      type: string
                    gender:
                      type: string
                    balance:
                      type: string
                    role_id:
                      type: integer
  "/users/sign_in":
    post:
      summary: Sign In
      tags:
      - users
      parameters: []
      responses:
        '200':
          description: Log in Sucessfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                  token:
                    type: string
                  refresh_token:
                    type: string
        '422':
          description: Invalid login Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  "/wastes":
    get:
      summary: Retrieves all wastes
      tags:
      - wastes
      responses:
        '200':
          description: wastes found
          content:
            application/json:
              schema:
                type: object
                properties:
                  wastes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        descriptions:
                          type: string
                        price:
                          type: float
                        category_id:
                          type: integer
    post:
      summary: Create new waste
      tags:
      - wastes
      parameters: []
      responses:
        '200':
          description: Sucessfully added data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      descriptions:
                        type: string
                      price:
                        type: float
                      category_id:
                        type: integer
                required:
                - name
                - address
        '404':
          description: Failed to add data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                descriptions:
                  type: string
                price:
                  type: float
                category_id:
                  type: integer
              required:
              - name
              - address
  "/wastes/{id}":
    get:
      summary: Find waste by id
      tags:
      - wastes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully find data
          content:
            application/json:
              schema:
                type: object
                properties:
                  wastes:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      descriptions:
                        type: string
                      price:
                        type: float
                      category_id:
                        type: integer
                  category:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '404':
          description: Failed to find data
    put:
      summary: Update waste by id
      tags:
      - wastes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully updated data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      descriptions:
                        type: string
                      price:
                        type: float
                      category_id:
                        type: integer
        '404':
          description: Failed to update data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                descriptions:
                  type: string
                price:
                  type: float
                category_id:
                  type: integer
              required:
              - name
              - descriptions
              - price
              - category_id
    delete:
      summary: Delete waste by id
      tags:
      - wastes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sucessfully deleted data
        '404':
          description: Failed to delete data
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
